;; -*-lisp-*-
(source gnu)
(source melpa)

(depends-on "flycheck")
(depends-on "flycheck-pyflakes")
(depends-on "helm")
(depends-on "discover")
(depends-on "ido-vertical-mode")
(depends-on "undo-tree")
(depends-on "multiple-cursors")
(depends-on "aggressive-indent")
(depends-on "mediawiki")
(depends-on "anzu")
(depends-on "pcre2el")
(depends-on "ess")
(depends-on "scroll-restore")

(depends-on "bug-hunter")
(depends-on "isearch+")
(depends-on "paredit")
