(source gnu)
(source melpa)

;; (depends-on "helm")
;; (depends-on "discover")
(depends-on "goto-chg")
(depends-on "ido-sort-mtime")
(depends-on "auctex")
(depends-on "cask-mode")
(depends-on "smart-comment")
(depends-on "sml-modeline")
(depends-on "dockerfile-mode")
(depends-on "flyspell-lazy")
(depends-on "cmake-font-lock")
(depends-on "latex-extra")
