(source gnu)
(source melpa)

(depends-on "flycheck")
(depends-on "helm")
(depends-on "discover")
(depends-on "ido-vertical-mode")
(depends-on "undo-tree")
(depends-on "multiple-cursors")
(depends-on "aggressive-indent")
