;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        backward-kill-line-or-newline
        backward-kill-line-or-region
        buf-move-left
        end-of-buffer
        fill-paragraph
        forward-sexp
        indent-for-tab-command
        jedi:dot-complete
        just-one-space-with-newline
        kill-line-or-region
        my-save-buffer-dtws
        osx-paste
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        alternating-scroll-down-line
        alternating-scroll-up-line
        newline-and-indent-conditionally
        python-indent-dedent-line-backspace
        ))
