;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        backward-kill-line-or-newline
        backward-kill-line-or-region
        beginning-of-visual-line
        buf-move-left
        end-of-buffer
        end-of-visual-line
        fill-paragraph
        flycheck-next-error
        forward-sexp
        goto-line
        indent-for-tab-command
        jedi:dot-complete
        just-one-space-with-newline
        kill-line-or-region
        kill-total-line
        markdown-electric-backquote
        markdown-enter-key
        markdown-outdent-or-delete
        my-save-buffer-dtws
        newline-and-indent-conditionally
        osx-paste
        python-indent-electric-colon
        reverse-zap-up-to-char
        vr/isearch-forward
        xterm-paste
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        alternating-scroll-down-line
        alternating-scroll-up-line
        beginning-of-buffer
        describe-key
        ido-find-file
        kmacro-end-or-call-macro
        smex
        suspend-frame
        ))
