;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-line-or-newline
        ))

(setq mc/cmds-to-run-once
      '(
        alternating-scroll-down-line
        alternating-scroll-up-line
        ))
